[greeter]
background = /usr/share/backgrounds/rayen-os/rayen-os-login-bg.png
theme-name = Adwaita-dark
icon-theme-name = Adwaita
font-name = Sans 11
xft-antialias = true
xft-hintstyle = hintfull
default-user-image = /usr/share/pixmaps/rayen-os-logo.png
hide-user-image = false
clock-format = %H:%M  -  %A %e %B
indicators = ~host;~spacer;~clock;~spacer;~session;~power
