---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    true

requirements:
    requiredStorage:    8
    requiredRam:        1
    internetCheckUrl:	https://github.com/yousifjilizi-del/rayen-os

    check:
        - storage
        - ram
        - power
        - root
    required:
        - root
        - storage
        - ram

geoip:
    style:  "none"
    url:    "https://geoip.ubuntu.com/lookup"
    selector: "CountryCode"
