---
modules-search: [ local ]

instances:
- id: remove_live_bits
  module: shellprocess
  config: shellprocess_remove_live_bits.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - initramfscfg
  - initramfs
  - grubcfg
  - bootloader
  - shellprocess@remove_live_bits
  - umount
- show:
  - finished

branding: rayen
prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: false
